package com.archivesentinel.api

import com.archivesentinel.domain.DeletionMode
import com.archivesentinel.domain.ExecutionMode
import com.archivesentinel.domain.OutputMode
import com.archivesentinel.domain.TdarrMode
import jakarta.validation.constraints.Min
import jakarta.validation.constraints.Max
import jakarta.validation.constraints.NotBlank

data class SetupRequest(
    val executionMode: ExecutionMode,
    val tdarrMode: TdarrMode,
    @field:NotBlank val tdarrBaseUrl: String,
    val managedTdarrEnabled: Boolean,
    @field:NotBlank val archiveRoot: String,
    @field:NotBlank val optimizedRoot: String,
    val stagingEnabled: Boolean,
    val stagingRoot: String?,
    @field:Min(1) val defaultRetentionDays: Int,
    val defaultDeletionMode: DeletionMode,
    val defaultOutputMode: OutputMode,
    val precheckExtensionOptions: List<String>,
    val enabledExtensions: List<String>,
    @field:Min(1) @field:Max(100) val estimatedOutputRatioPercent: Int,
    @field:NotBlank val outputContainerExtension: String,
    @field:Min(0) val durationToleranceSeconds: Double,
    val tdarrCodecsToExclude: String,
    @field:NotBlank val tdarrTranscodeArguments: String,
    val mediaFfmpegPath: String,
    val mediaFfprobePath: String,
    @field:Min(1) val reportIntervalHours: Int,
    val reportRecipients: String,
    val smtpHost: String,
    @field:Min(1) val smtpPort: Int,
    val smtpUsername: String,
    val smtpPassword: String,
    val smtpAuth: Boolean,
    val smtpStartTls: Boolean,
    val smtpFrom: String,
    @field:Min(1) val scanThreads: Int,
    @field:Min(1) val analysisThreads: Int,
    @field:Min(1) val validationThreads: Int,
    @field:Min(1) val fileOpsThreads: Int,
    @field:Min(1) val tdarrSubmissionConcurrency: Int,
    @field:Min(1) val backgroundScanRefreshMinutes: Int,
    val maxAvailableThreads: Int? = null,
)

data class SettingsResponse(
    val setupCompleted: Boolean,
    val executionMode: ExecutionMode,
    val tdarrMode: TdarrMode,
    val tdarrBaseUrl: String,
    val managedTdarrEnabled: Boolean,
    val archiveRoot: String,
    val optimizedRoot: String,
    val stagingEnabled: Boolean,
    val stagingRoot: String?,
    val defaultRetentionDays: Int,
    val defaultDeletionMode: DeletionMode,
    val defaultOutputMode: OutputMode,
    val precheckExtensionOptions: List<String>,
    val enabledExtensions: List<String>,
    val estimatedOutputRatioPercent: Int,
    val outputContainerExtension: String,
    val durationToleranceSeconds: Double,
    val tdarrCodecsToExclude: String,
    val tdarrTranscodeArguments: String,
    val mediaFfmpegPath: String,
    val mediaFfprobePath: String,
    val reportIntervalHours: Int,
    val reportRecipients: String,
    val smtpHost: String,
    val smtpPort: Int,
    val smtpUsername: String,
    val smtpPassword: String,
    val smtpAuth: Boolean,
    val smtpStartTls: Boolean,
    val smtpFrom: String,
    val scanThreads: Int,
    val analysisThreads: Int,
    val validationThreads: Int,
    val fileOpsThreads: Int,
    val tdarrSubmissionConcurrency: Int,
    val backgroundScanRefreshMinutes: Int,
    val maxAvailableThreads: Int,
)
